import { exportCsvWorkbook, exportExcelWorkbook } from '../../../utils/excelExport'
import { getColumnTextValue } from '../config/accountBoardColumns'
import { ACCOUNT_COMPACT_EXPORT_COLUMNS, ACCOUNT_EXPORT_COLUMNS } from '../config/accountExportColumns'

// Per-board overrides keyed by `filePrefix`. Drives the sheet tab name and
// subtitle that appear at the top of every exported file so each board reads
// like a distinct report instead of a generic "Accounts" sheet.
const BOARD_EXPORT_PRESETS = {
  'view-all-accounts':    { sheetName: 'Accounts',        subtitle: 'View all accounts export' },
  'my-group-accounts':    { sheetName: 'Group Accounts',  subtitle: 'My group accounts export' },
  'my-accounts':          { sheetName: 'My Accounts',     subtitle: 'My accounts export' },
  'search-account':       { sheetName: 'Search Account',  subtitle: 'Search results export' },
  'account-source-view':  { sheetName: 'Source View',     subtitle: 'Source-wise account export' },
  'weekly-reports-all':   { sheetName: 'Weekly Report',   subtitle: 'Weekly accounts snapshot' },
  'sw-baroda-mum':        { sheetName: 'SW BR/MUM',       subtitle: 'Baroda / Mumbai accounts' },
  'user-wise-leads':      { sheetName: 'User Wise Leads', subtitle: 'User-wise lead export' },
  'converted-accounts':   { sheetName: 'Converted',       subtitle: 'Converted accounts export' },
  'daily-fresh-leads':    { sheetName: 'Daily Fresh',     subtitle: 'Daily fresh leads export' },
  'no-follow-leads':      { sheetName: 'No Follow Leads', subtitle: 'No-follow leads export' },
}

const resolveBoardPreset = (filePrefix) => BOARD_EXPORT_PRESETS[filePrefix] || { sheetName: 'Accounts', subtitle: 'Detailed account export' }

// Metadata order matches the standard layout diagram:
//   Board → Total Records → Selected Stage → Export Scope.
// (auto-added by the util: Company Name, Report Title, Export Date, Generated By)
const buildAccountMetadata = ({ scopeLabel, stageLabel, boardTitle, rowCount }) => {
  const entries = []
  if (boardTitle)  entries.push({ label: 'Board',          value: boardTitle })
  entries.push({ label: 'Total Records', value: String(rowCount) })
  if (stageLabel)  entries.push({ label: 'Selected Stage', value: stageLabel })
  if (scopeLabel)  entries.push({ label: 'Export Scope',   value: scopeLabel })
  return entries
}

export const exportAccountsBoard = ({ rows = [], columns = [], stageKey = 'all', filePrefix = 'my-group-accounts' }) => {
  const exportColumns = columns.filter((column) => column.exportable)
  const dateStamp = new Date().toISOString().slice(0, 10)
  const preset = resolveBoardPreset(filePrefix)

  exportCsvWorkbook({
    filename: `${filePrefix}-${stageKey}-${dateStamp}.csv`,
    title: 'Accounts Board Export',
    subtitle: stageKey === 'all' ? 'All Stages' : `Stage: ${stageKey}`,
    sheetName: preset.sheetName,
    metadata: [
      { label: 'Selected Stage', value: stageKey },
      { label: 'Total Records',  value: String(rows.length) },
    ],
    columns: [
      { key: '__serialNumber', label: 'Sr. No.', align: 'center', width: 8 },
      ...exportColumns.map((column) => ({
        key: column.key,
        label: column.label,
        align: 'left',
        formatter: (_value, row) => getColumnTextValue(column, row),
      })),
    ],
    rows,
  })
}

export const exportAccountsBoardFull = ({
  rows = [],
  scopeKey = 'current-stage',
  scopeLabel = 'Current Stage',
  boardTitle = 'My Group Accounts',
  stageLabel = 'All Stages',
  filePrefix = 'my-group-accounts',
}) => {
  const dateStamp = new Date().toISOString().slice(0, 10)
  const preset = resolveBoardPreset(filePrefix)

  exportCsvWorkbook({
    filename: `${filePrefix}-${scopeKey}-${dateStamp}.csv`,
    title: boardTitle,
    subtitle: preset.subtitle,
    sheetName: preset.sheetName,
    metadata: buildAccountMetadata({ scopeLabel, stageLabel, boardTitle, rowCount: rows.length }),
    columns: ACCOUNT_EXPORT_COLUMNS,
    rows,
  })
}

export const exportAccountsBoardWorkbook = ({
  rows = [],
  scopeKey = 'current-stage',
  scopeLabel = 'Current Stage',
  boardTitle = 'Search Account',
  stageLabel = 'All Stages',
  filePrefix = 'search-account',
}) => {
  const dateStamp = new Date().toISOString().slice(0, 10)
  const preset = resolveBoardPreset(filePrefix)

  exportExcelWorkbook({
    filename: `${filePrefix}-${scopeKey}-${dateStamp}.xlsx`,
    title: `${boardTitle} Report`,
    subtitle: stageLabel === 'All Stages' ? 'Compact account export' : `${stageLabel} - compact account export`,
    sheetName: preset.sheetName,
    columns: ACCOUNT_COMPACT_EXPORT_COLUMNS,
    rows,
    metadata: [
      { label: 'Rows', value: String(rows.length) },
      { label: 'Scope', value: scopeLabel },
      ...(stageLabel ? [{ label: 'Stage', value: stageLabel }] : []),
    ],
  })
}
