export const ACCOUNT_CATEGORY_OPTIONS = ['LUMOS', 'SWATI'];

export const CUSTOMER_TYPE_OPTIONS = [
  'Consultant',
  'Contractor',
  'End-User',
  'Internal Lead',
  'OEM',
  'Project Manager',
];

export const INDUSTRY_TYPE_OPTIONS = [
  'AUTOMATION',
  'AGRICULTURE & FOOD',
  'AUTOMOBILE',
  'CEMENT',
  'CERAMIC & TILES',
  'CONTRACTOR',
  'CONSULTANT',
  'DAIRY',
  'DATA CENTER',
  'ENGINEERING',
  'ENERGY',
  'FERTILIZER',
  'GOVERNMENT',
  'HOTELS & HOSPITAL',
  'INSTITUTES',
  'INFRASTRUCTURE',
  'IT / COMMERCIAL',
  'OIL & GAS',
  'PHARMACEUTICAL & HEALTH CARE',
  'PAINT / CHEMICAL',
  'PAPER, PRINTING & PACKAGING',
  'PORTS / AIR PORTS',
  'POWER SECTOR',
  'POWER GENERATION',
  'RESIDENTIAL',
  'STEEL / METAL/TUBE/GLASS',
  'SOLAR',
  'TEXTILE',
  'WATER SAGMENT',
  'OTHER',
];

export const STATE_OPTIONS = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const REMINDER_MODE_OPTIONS = ['call', 'meeting', 'visit', 'email'];
