const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CONNECT_ERROR: 'connect_error',
  LOGIN: 'login',
  JOIN_ROOM: 'joinRoom',
  USERS_ONLINE: 'users:online',
  USER_ONLINE: 'userOnline',
  USER_OFFLINE: 'userOffline',
  CREATE_LEAD: 'createLead',
  UPDATE_LEAD: 'updateLead',
  LEAD_ASSIGNED: 'leadAssigned',
  DASHBOARD_UPDATE: 'dashboardUpdate',
  PRIVATE_NOTIFICATION: 'privateNotification',
  FORM_UPDATED: 'formUpdated',
  RECEIVE_MESSAGE: 'receiveMessage',
  ACCOUNT_CREATE: 'account:create',
  ACCOUNT_UPDATE: 'account:update',
  ACCOUNT_DELETE: 'account:delete',
  NEW_LEAD: 'newLead',
  LEAD_UPDATED: 'leadUpdated',
  NOTIFICATION: 'notification',
  SEND_MESSAGE: 'sendMessage',
  SEND_MESSAGE_LEGACY: 'message:send',
  DASHBOARD_TABS_UPDATE: 'dashboard-tabs:update',
  DEAL_CREATE: 'deal:create',
  DEAL_UPDATE: 'deal:update',
  DEAL_DELETE: 'deal:delete',
  DEAL_CREATED: 'deal:created',
  DEAL_UPDATED: 'deal:updated',
  DEAL_DELETED: 'deal:deleted',
  TASK_CREATE: 'task:create',
  TASK_UPDATE: 'task:update',
  TASK_DELETE: 'task:delete',
  TASK_CREATED: 'task:created',
  TASK_UPDATED: 'task:updated',
  TASK_DELETED: 'task:deleted',
  SUPPORT_REQUEST_CREATE: 'support-request:create',
  SUPPORT_REQUEST_UPDATE: 'support-request:update',
  SUPPORT_REQUEST_CREATED: 'support-request:created',
  SUPPORT_REQUEST_UPDATED: 'support-request:updated',
  USER_CREATED: 'user:created',
  USER_UPDATED: 'user:updated',
  USER_STATUS_CHANGED: 'user:status:changed',
  USER_DELETED: 'user:deleted',
  USER_TYPE_CREATED: 'user-type:created',
  USER_TYPE_UPDATED: 'user-type:updated',
  USER_TYPE_DELETED: 'user-type:deleted',
}

const SOCKET_ROOMS = {
  user: (userId) => `user:${userId}`,
  role: (role) => `role:${role}`,
  company: (companyId) => `company:${companyId}`,
  companyRole: (companyId, role) => `company:${companyId}:role:${role}`,
}

module.exports = {
  SOCKET_EVENTS,
  SOCKET_ROOMS,
}
