import { ACCOUNT_ACTION_MAP, ACCOUNT_ACTIONS } from './accountActions'

export const ADMIN_ACCOUNTS_BOARD_VIEWS = {
  viewAll: {
    key: 'viewAll',
    queryValue: 'view-all',
    route: '/admin/accounts',
    heroEyebrow: 'Admin Accounts Workspace',
    heroTitle: 'View All Accounts',
    heroCopy: 'Shared legacy CRM board for all admin accounts with stage tabs, filters, drawer details, and live socket-backed updates.',
    boardTitle: 'All Accounts Board',
    exportFilePrefix: 'view-all-accounts',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'new',
    hiddenStageKeys: ['rejected'],
    showStageTabs: false,
    rowActionMenuEnabled: false,
    rowActions: [
      ACCOUNT_ACTION_MAP['view-account'],
      ACCOUNT_ACTION_MAP['converted-deal'],
      ACCOUNT_ACTION_MAP['view-linked-deal'],
    ],
    showAddAccountButton: true,
    titlebarActions: {
      showBulk: true,
      showExportIcon: true,
    },
  },
  myGroup: {
    key: 'myGroup',
    queryValue: 'my-group',
    route: '/admin/accounts/my-group-accounts',
    heroEyebrow: 'Admin Legacy CRM Board',
    heroTitle: 'My Group Accounts',
    heroCopy: 'Shared legacy CRM board for group-level account tracking with the same real-time stream, drawer details, and staged workflow tabs.',
    boardTitle: 'My Group Accounts Board',
    exportFilePrefix: 'my-group-accounts',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'new',
    showStageTabs: true,
    rowActionMenuEnabled: false,
    showExportButton: true,
    titlebarActions: {
      showBulk: true,
    },
  },
  myAccounts: {
    key: 'myAccounts',
    queryValue: 'my-accounts',
    route: '/admin/accounts/my-accounts',
    heroEyebrow: 'Admin Personal Workspace',
    heroTitle: 'My Accounts',
    heroCopy: 'Your own live account board with stage tabs, direct account opening, and legacy CRM table behavior.',
    boardTitle: 'My Accounts Board',
    exportFilePrefix: 'my-accounts',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'new',
    showStageTabs: true,
    rowActionMenuEnabled: false,
    showAddAccountButton: false,
    showRefreshButton: false,
    showExportButton: false,
    titlebarActions: {
      showHelp: false,
      showBulk: true,
      showExportIcon: true,
      showFilterIcon: true,
    },
  },
  searchAccount: {
    key: 'searchAccount',
    queryValue: 'search-account',
    route: '/admin/accounts/search',
    heroEyebrow: 'Admin Search Workspace',
    heroTitle: 'Search Account',
    heroCopy: 'Search account records in a compact CRM-style board with direct column filters, real-time updates, export options, and row action menus.',
    boardTitle: 'Accounts Search Board',
    exportFilePrefix: 'search-account',
    exportKind: 'excel',
    exportButtonLabel: 'Export Excel',
    defaultStage: 'new',
    hiddenStageKeys: ['rejected'],
    showStageTabs: false,
    showRefreshButton: false,
    showExportButton: false,
    rowActionMenuEnabled: false,
    rowActions: [
      ACCOUNT_ACTION_MAP['view-account'],
      ACCOUNT_ACTION_MAP['converted-deal'],
      ACCOUNT_ACTION_MAP['view-linked-deal'],
    ],
    showAddAccountButton: true,
    titlebarActions: {
      showBulk: true,
      showFilterIcon: true,
    },
  },
  accountSourceView: {
    key: 'accountSourceView',
    queryValue: 'source-view',
    route: '/admin/accounts/source-view',
    heroEyebrow: 'Admin Source Workspace',
    heroTitle: 'Account Source View',
    heroCopy: 'Track live account records by source bucket with compact search columns and direct view-account access.',
    boardTitle: 'Account Source View',
    exportFilePrefix: 'account-source-view',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'call',
    showStageTabs: true,
    selectedTabField: 'sourceBucketKey',
    summaryMode: 'source',
    showRefreshButton: false,
    showExportButton: false,
    rowActionMenuEnabled: true,
    rowActions: [ACCOUNT_ACTION_MAP['view-account']],
    mainButtonBehavior: 'toggleMenu',
    titlebarActions: {
      showExportIcon: true,
      showColumnsIcon: true,
      showRefreshIcon: true,
      showLoadMenu: true,
    },
  },
  weeklyReportsAll: {
    key: 'weeklyReportsAll',
    queryValue: 'weekly-reports-all',
    route: '/admin/accounts/weekly-reports-all',
    heroEyebrow: 'Admin Weekly Workspace',
    heroTitle: 'Weekly reports-ALL',
    heroCopy: 'Live weekly account reporting with a compact CRM table, search filters, and direct account viewing.',
    boardTitle: 'Weekly reports-ALL',
    exportFilePrefix: 'weekly-reports-all',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'weekly_reports_all',
    showStageTabs: false,
    showRecordCountInHeroTitle: true,
    summaryMode: 'weekly',
    summaryBanner: 'SWATI',
    criteriaLabel: 'Account Date is within last 7 day(s)',
    showRefreshButton: false,
    showExportButton: false,
    rowActionMenuEnabled: true,
    rowActions: [ACCOUNT_ACTION_MAP['view-account']],
    mainButtonBehavior: 'toggleMenu',
    titlebarActions: {
      showBulk: true,
      showExportIcon: true,
      showColumnsIcon: true,
      showFilterIcon: true,
      showRefreshIcon: true,
      showMoreMenu: true,
    },
  },
  swBarodaMum: {
    key: 'swBarodaMum',
    queryValue: 'sw-baroda-mum',
    route: '/admin/accounts/sw-baroda-mum',
    heroEyebrow: 'Admin Team Workspace',
    heroTitle: 'SW-Baroda / Mum',
    heroCopy: 'Live owner-wise account board for the SW-Baroda / Mum team with compact search and direct account viewing.',
    boardTitle: 'SW-Baroda / Mum',
    exportFilePrefix: 'sw-baroda-mum',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'jagruti-parmar',
    showStageTabs: true,
    showRecordCountInHeroTitle: true,
    selectedTabField: 'ownerBucketKey',
    summaryMode: 'owner',
    showRefreshButton: false,
    showExportButton: false,
    rowActionMenuEnabled: true,
    rowActions: [ACCOUNT_ACTION_MAP['view-account']],
    mainButtonBehavior: 'toggleMenu',
  },
  userWiseLeads: {
    key: 'userWiseLeads',
    queryValue: 'user-wise-leads',
    route: '/admin/accounts/user-wise-leads',
    heroEyebrow: 'Admin User Workspace',
    heroTitle: 'User Wise Leads',
    heroCopy: 'Live user-wise lead tracking with fixed team tabs, compact search, and the full account action menu.',
    boardTitle: 'User Wise Leads',
    exportFilePrefix: 'user-wise-leads',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'atish-shah',
    showStageTabs: true,
    showRecordCountInHeroTitle: true,
    selectedTabField: 'userBucketKey',
    summaryMode: 'owner',
    showRefreshButton: false,
    showExportButton: false,
    rowActionMenuEnabled: true,
    rowActions: ACCOUNT_ACTIONS,
    mainButtonBehavior: 'toggleMenu',
  },
  dailyFreshLeads: {
    key: 'dailyFreshLeads',
    queryValue: 'daily-fresh-leads',
    route: '/accounts/daily-fresh-leads',
    heroEyebrow: 'User Daily Workspace',
    heroTitle: 'Daily Fresh Leads',
    heroCopy: 'Track accounts added today with real-time CRM updates, compact search columns, and direct details access.',
    boardTitle: 'Daily Fresh Leads Board',
    exportFilePrefix: 'daily-fresh-leads',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'daily_fresh_leads',
    showStageTabs: false,
    showRecordCountInHeroTitle: true,
    showRefreshButton: false,
    showExportButton: false,
    rowActionMenuEnabled: true,
  },
  noFollowLeads: {
    key: 'noFollowLeads',
    queryValue: 'no-follow-leads',
    route: '/accounts/no-follow-leads',
    heroEyebrow: 'User Action Workspace',
    heroTitle: 'No Follow Leads',
    heroCopy: 'Manage active leads that do not have any follow-up reminders scheduled.',
    boardTitle: 'No Follow Leads Board',
    exportFilePrefix: 'no-follow-leads',
    exportKind: 'csv',
    exportButtonLabel: 'Export CSV',
    defaultStage: 'no_follow_leads',
    showStageTabs: false,
    showRecordCountInHeroTitle: true,
    showRefreshButton: false,
    showExportButton: false,
    rowActionMenuEnabled: true,
  },
}

export const getAdminAccountsBoardView = (variantKey = 'myGroup') =>
  ADMIN_ACCOUNTS_BOARD_VIEWS[variantKey] || ADMIN_ACCOUNTS_BOARD_VIEWS.myGroup

export const getAdminAccountsBoardViewByQuery = (queryValue) =>
  Object.values(ADMIN_ACCOUNTS_BOARD_VIEWS).find((view) => view.queryValue === queryValue) ||
  ADMIN_ACCOUNTS_BOARD_VIEWS.myGroup

export const buildAdminAccountsBoardUrl = (variantKey = 'myGroup', queryString = '') => {
  const view = getAdminAccountsBoardView(variantKey)
  return `${view.route}${queryString}`
}
